In [85]:
import pandas as pd
import numpy as np
import string 

from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [86]:
df=pd.read_csv("Formspring.csv")
df.head()

                                                text answer
0  Q: what&#039;s your favorite song? :D<br>A: I ...     No
1                     Q: <3<br>A: </3 ? haha jk! <33     No
2  Q: &quot;hey angel  you duh sexy&quot;<br>A: R...     No
3                                     Q: (:<br>A: ;(     No
4  Q: ******************MEOWWW*******************...     No

In [87]:
print(f"Dataset has {df.shape[0]} rows and {df.shape[1] } columns ")

Dataset has 13147 rows and 2 columns

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13147 entries, 0 to 13146
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    13147 non-null  object
 1   answer  13147 non-null  object
dtypes: object(2)
memory usage: 205.6+ KB

In [89]:
df.describe()

                                                     text answer
count                                               13147  13147
unique                                              13144      2
top     Q: Wait. Are you Cheyenne? I sent a request to...     No
freq                                                    3  12295

In [90]:
df.isnull().sum()

text      0
answer    0
dtype: int64

In [91]:
df["answer"].value_counts()

answer
No     12295
Yes      852
Name: count, dtype: int64

In [92]:
formspring_text_features=df["text"].copy()
tfid_vectorizer=TfidfVectorizer(encoding="english")
formspring_features=tfid_vectorizer.fit_transform(formspring_text_features)

print("Text Features from the Dataset - Formsprong.csv:")
print('-'*63)
print(formspring_text_features)

Text Features from the Dataset - Formsprong.csv:
---------------------------------------------------------------
0        Q: what&#039;s your favorite song? :D<br>A: I ...
1                           Q: <3<br>A: </3 ? haha jk! <33
2        Q: &quot;hey angel  you duh sexy&quot;<br>A: R...
3                                           Q: (:<br>A: ;(
4        Q: ******************MEOWWW*******************...
                               ...
13142    Q: Youre at a party and your friend who drove ...
13143    Q: Youu2019re awesome :] Give yourself a compl...
13144    Q: Yu play with yurself ?<br>A: all the time. ...
13145    Q: yukk beer is disgusting. i can only drink i...
13146    Q: if i told u den it would make it all the le...
Name: text, Length: 13147, dtype: object

In [93]:
print("Features from the Dataset-Formspring.csv:")
print('-'*53)
print(formspring_features)

Features from the Dataset-Formspring.csv:
-----------------------------------------------------
  (0, 17947)	0.15984947496542218
  (0, 4)	0.21166783975854714
  (0, 18614)	0.16445580974678042
  (0, 6020)	0.5901629635353193
  (0, 15130)	0.3373860496444202
  (0, 2417)	0.06294444269439241
  (0, 9775)	0.19038717708585326
  (0, 16688)	0.26377533756496274
  (0, 10321)	0.30068023170403524
  (0, 15135)	0.43794630875263
  (0, 16619)	0.13666204960704684
  (0, 7574)	0.17265193864975523
  (1, 2417)	0.10517467075209344
  (1, 7324)	0.3741534117644444
  (1, 8965)	0.6831137869399058
  (1, 212)	0.6183066126040022
  (2, 2417)	0.05634780356239197
  (2, 7324)	0.20045437554062448
  (2, 13327)	0.5094343603709673
  (2, 7765)	0.2886547397744486
  (2, 1044)	0.4381590967996309
  (2, 18600)	0.0865259371250384
  (2, 5157)	0.42483910836891375
  (2, 14472)	0.3371973861965128
  (2, 13501)	0.2132496484348259
  :	:
  (13145, 5128)	0.22992749038686963
  (13145, 4804)	0.3182924140169115
  (13145, 17605)	0.26767063177828804
  (13145, 18674)	0.342542801251734
  (13145, 15556)	0.342542801251734
  (13146, 2417)	0.03686701393993486
  (13146, 9775)	0.11151114238452552
  (13146, 8747)	0.28028822588824825
  (13146, 11937)	0.11252303052026807
  (13146, 12398)	0.16498769394713392
  (13146, 18666)	0.2309540440309204
  (13146, 11563)	0.11626454228687172
  (13146, 8261)	0.11102590429489728
  (13146, 16341)	0.08059985698983853
  (13146, 5916)	0.21094756057872716
  (13146, 876)	0.13564887505027856
  (13146, 18297)	0.22936079989899824
  (13146, 10250)	0.3303386104409981
  (13146, 6645)	0.21063379686410189
  (13146, 16647)	0.1973906459837876
  (13146, 2991)	0.2650070297345777
  (13146, 9999)	0.34601213885639953
  (13146, 9695)	0.2650070297345777
  (13146, 4501)	0.28922053005809745
  (13146, 14218)	0.3609604266491804

In [94]:
saved_formspring_df=pd.DataFrame(formspring_text_features)
saved_formspring_df.to_csv("Formspring Text Features.csv")

**Label encoding**:sklearn requires all inputs to be numeric, we need to convert all categorical variables (string labels) into numeric by encoding 
the categories i.e 'No', 'yes' to 0,1 sklearn provides LabelEncoder library for encoding labels between 0 to n-1 discrete classes,where n is the number of class-labels

In [96]:
from sklearn.preprocessing import LabelEncoder

column=["answer"]
print("Column:",column)

Column: ['answer']

In [97]:
label_encoder=LabelEncoder()

for i in column:
    df[i]=label_encoder.fit_transform(df[i])

print("Dataset Data Types:")
print('-'*33)
print(df.dtypes)

Dataset Data Types:
---------------------------------
text      object
answer     int64
dtype: object

In [98]:
print("First 10 Elements from the 'Dataset - Formspring.csv':")
print('-' * 63)
df.head()

First 10 Elements from the 'Dataset - Formspring.csv':
---------------------------------------------------------------

                                                text  answer
0  Q: what&#039;s your favorite song? :D<br>A: I ...       0
1                     Q: <3<br>A: </3 ? haha jk! <33       0
2  Q: &quot;hey angel  you duh sexy&quot;<br>A: R...       0
3                                     Q: (:<br>A: ;(       0
4  Q: ******************MEOWWW*******************...       0

In [99]:
print("Last 10 Elements from the 'Dataset - Formspring.csv':")
print('-' * 63)
df.tail()

Last 10 Elements from the 'Dataset - Formspring.csv':
---------------------------------------------------------------

                                                    text  answer
13142  Q: Youre at a party and your friend who drove ...       0
13143  Q: Youu2019re awesome :] Give yourself a compl...       0
13144  Q: Yu play with yurself ?<br>A: all the time. ...       0
13145  Q: yukk beer is disgusting. i can only drink i...       0
13146  Q: if i told u den it would make it all the le...       0

In [100]:
formspring_features_train,formspring_features_test,formspring_labels_train,formspring_labels_test=train_test_split(
    formspring_features,
    df["answer"],
    test_size=0.3,
    random_state=4861
)

In [101]:
print("Features Train from the 'Dataset - Formspring.csv':")
print('-' * 53)
print(formspring_features_train)

Features Train from the 'Dataset - Formspring.csv':
-----------------------------------------------------
  (0, 2417)	0.03554805974627196
  (0, 16619)	0.07718029577394415
  (0, 18600)	0.054586496510325856
  (0, 9954)	0.10429408251589235
  (0, 10481)	0.10405181432957193
  (0, 9348)	0.12154826875015336
  (0, 4873)	0.08636409381158049
  (0, 12620)	0.4254544835107159
  (0, 8361)	0.11959751173117253
  (0, 2859)	0.12741497551261466
  (0, 8079)	0.11654039500223604
  (0, 2720)	0.10971778532157818
  (0, 15542)	0.16819394890336758
  (0, 16149)	0.26280618295286606
  (0, 13058)	0.26801765201244987
  (0, 12703)	0.6468133399762015
  (0, 1905)	0.34804670737560567
  (1, 2417)	0.04981611402851899
  (1, 18600)	0.076496077535172
  (1, 7044)	0.23073939557861475
  (1, 14338)	0.23073939557861475
  (1, 15567)	0.2641370614165871
  (1, 17611)	0.4186836846730796
  (1, 12013)	0.28504038186951564
  (1, 18526)	0.3199978896093582
  :	:
  (9201, 8261)	0.15428670154346316
  (9201, 16365)	0.10697073705480287
  (9201, 2040)	0.16685610328188755
  (9201, 16341)	0.2800131680712769
  (9201, 8079)	0.08397939220696377
  (9201, 2720)	0.07906299721588791
  (9201, 11044)	0.11432446663981545
  (9201, 18297)	0.15936515673762952
  (9201, 17984)	0.23759326724741997
  (9201, 16411)	0.11495388525504753
  (9201, 16557)	0.10628023570928685
  (9201, 13751)	0.1688662360165458
  (9201, 17749)	0.08741352613745981
  (9201, 11590)	0.10410439118670733
  (9201, 2911)	0.14613703402671394
  (9201, 13682)	0.21871276545668492
  (9201, 7491)	0.15536605801754289
  (9201, 7882)	0.13986732604734814
  (9201, 7865)	0.16454678837720468
  (9201, 17385)	0.14768999730080823
  (9201, 4172)	0.16685610328188755
  (9201, 12277)	0.17281496736159643
  (9201, 2749)	0.3248571066888926
  (9201, 10037)	0.22266149680173553
  (9201, 4519)	0.2508036028578548

In [102]:
print("Features Test from the 'Dataset - Formspring.csv':")
print('-' * 53)
print(formspring_features_test)

Features Test from the 'Dataset - Formspring.csv':
-----------------------------------------------------
  (0, 2417)	0.0871288068770038
  (0, 11539)	0.4348566941761628
  (0, 757)	0.543294262374109
  (0, 17272)	0.7128390919511511
  (1, 17947)	0.07632386129324027
  (1, 2417)	0.03005429273024719
  (1, 16619)	0.06525248406674125
  (1, 18600)	0.04615043850352481
  (1, 1149)	0.13369782864014165
  (1, 1030)	0.07126466246482528
  (1, 11716)	0.16632759683822806
  (1, 18021)	0.10472726260005898
  (1, 10053)	0.1095021665550937
  (1, 8720)	0.08034314350188487
  (1, 8434)	0.08303028290530447
  (1, 18166)	0.0998524702814988
  (1, 18621)	0.1610928410049845
  (1, 16341)	0.26282266309230107
  (1, 18273)	0.1627476236661054
  (1, 16329)	0.08283111522658117
  (1, 876)	0.22116415535751952
  (1, 12344)	0.11916159343785462
  (1, 15258)	0.19520386014948365
  (1, 3903)	0.1329171537679675
  (1, 1921)	0.2889582677005952
  :	:
  (3942, 11963)	0.2631816685639098
  (3942, 2076)	0.2631816685639098
  (3942, 12047)	0.23237485951474748
  (3942, 2016)	0.23237485951474748
  (3943, 17947)	0.17189064624886682
  (3943, 2417)	0.06768593349996493
  (3943, 7574)	0.18565749632299866
  (3943, 18600)	0.10393641732250837
  (3943, 4873)	0.1644431328246662
  (3943, 11716)	0.18729501904849333
  (3943, 2843)	0.5414277882966002
  (3943, 9260)	0.3551875520752377
  (3943, 15140)	0.6627047005787028
  (3944, 2417)	0.028518757349242398
  (3944, 18600)	0.04379251806243828
  (3944, 9080)	0.10068093046543994
  (3944, 2859)	0.10221983408489682
  (3944, 6923)	0.14453091000891288
  (3944, 13702)	0.24349642379417832
  (3944, 12667)	0.23632924859567156
  (3944, 6873)	0.5584473338176286
  (3944, 10889)	0.5584473338176286
  (3944, 7763)	0.2792236669088143
  (3944, 1704)	0.2676603058770932
  (3944, 14319)	0.2594559706591137

In [103]:
print("First 10 Elements from Formspring Labels Train:")
print('-' * 53)
formspring_labels_train.head(10)

First 10 Elements from Formspring Labels Train:
-----------------------------------------------------

5634     0
3350     0
8939     0
5109     0
1001     0
5754     0
12939    0
7619     0
5705     0
10248    0
Name: answer, dtype: int64

In [123]:
print("Last 10 Elements from Formspring Labels Test:")
print('-' * 53)
formspring_labels_test.tail(10)

Last 10 Elements from Formspring Labels Test:
-----------------------------------------------------

6376     0
5645     0
54       0
9025     0
11808    0
7440     0
9434     0
2928     0
7176     0
7887     0
Name: answer, dtype: int64

In [127]:
from sklearn.model_selection import GridSearchCV

from sklearn.svm import(SVR,SVC)
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import  DecisionTreeClassifier
from sklearn.linear_model import(Ridge,RidgeClassifier,SGDRegressor,SGDClassifier,LogisticRegression)
from sklearn.metrics import(
    accuracy_score,
    precision_score,
    recall_score, 
    f1_score, 
    confusion_matrix, 
    classification_report
)

from matplotlib import style
import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")