In [ ]:
import nltk
import csv
import numpy as np
import codecs

In [ ]:
def load_training_data():
    with open("Spam.csv", 'r', encoding="UTF-8", errors="ignore") as csvfile:
        reader = csv.reader(csvfile, delimiter=',', quotechar='"')
        total_list = []
        X = []
        Y = []

        for row in reader:
            # print(row)
            if row[1] == "neutral":
                continue
            else:
                # print(row[0])
                X.append(row[0])  # Message
                Y.append(row[1])  # Class
                total_list.append(row)

        classes = np.unique(Y)

        for each_class in classes:
            print(each_class)

        print((('-' * 33) + "\n") + "Length of Total List: ", len(total_list))

    return (total_list)


spam_ham = load_training_data()

In [ ]:
# Text Preprocessing(NLP)
messages=[]
for (words,category) in spam_ham:
    words_filtered=[e.lower() for e in words.split() if len(e)>=3]
    messages.append((words_filtered,category))

# Merge all words from messages into a single list
def get_words_in_messages(messages):
    all_words=[]

    for(words,category) in messages:
        all_words.extend(words)
    return all_words
    
# Collection of unique words
def get_word_features(wordlist):
    wordlist=nltk.FreqDist(wordlist) # Frequency
    word_features=wordlist.keys() # unique words

    return word_features

# Text Document into a feature Dictionary
def extract_features(document):
    document_words=set(document) # set for faster lookup ,remove duplicates and makes checking easier
    features={}

    for word in word_features:
        features["Contains:(%s)" % word]=(word in document_words) # create binary features(True/False)
    return features

word_features=get_word_features(get_words_in_messages(messages))
training_set=nltk.classify.apply_features(extract_features,messages)
classifier=nltk.NaiveBayesClassifier.train(training_set)

In [19]:
print("RESULTS".center(90, '_') + "\n" +
      "Accuracy:" + "\t" + f"{(nltk.classify.util.accuracy(classifier, training_set)) * 100}%", end="\n\n")
classifier.show_most_informative_features(20)

print('_' * 90)

_________________________________________RESULTS__________________________________________
Accuracy:	99.1925354387224%

Most Informative Features
          Contains:(100) = True             spam : ham    =    161.3 : 1.0
       Contains:(latest) = True             spam : ham    =    148.4 : 1.0
      Contains:(message) = True            Class : ham    =     96.5 : 1.0
         Contains:(2000) = True             spam : ham    =     92.5 : 1.0
        Contains:(nokia) = True             spam : ham    =     91.2 : 1.0
        Contains:(await) = True             spam : ham    =     83.9 : 1.0
         Contains:(now!) = True             spam : ham    =     82.7 : 1.0
      Contains:(service) = True             spam : ham    =     69.5 : 1.0
        Contains:(video) = True             spam : ham    =     68.4 : 1.0
          Contains:(txt) = True             spam : ham    =     66.8 : 1.0
         Contains:(code) = True             spam : ham    =     66.7 : 1.0
     Contains:(selected) = True             spam : ham    =     65.8 : 1.0
      Contains:(network) = True             spam : ham    =     60.6 : 1.0
     Contains:(services) = True             spam : ham    =     58.1 : 1.0
      Contains:(attempt) = True             spam : ham    =     55.5 : 1.0
       Contains:(orange) = True             spam : ham    =     55.5 : 1.0
       Contains:(caller) = True             spam : ham    =     53.8 : 1.0
Contains:(congratulations) = True             spam : ham    =     53.8 : 1.0
       Contains:(player) = True             spam : ham    =     53.8 : 1.0
      Contains:(voucher) = True             spam : ham    =     53.8 : 1.0
__________________________________________________________________________________________
done

In [21]:
# Read and store test text
def load_test_data():
    test_messages=[]
    test=codecs.open("Spamtest.txt",'r',"UTF-8")

    for each_value in test:
        test_messages.append(each_value)
    return test_messages

In [29]:
# Load test file containing message only
run_messages=load_test_data()
spam_count=0
ham_count=0

for each_messages in run_messages:
    values=classifier.classify(extract_features(each_messages.split()))


    print("Message:",each_messages,":",values)

    if values=="ham":
        ham_count+=1
    else:
        spam_count+=1

        print('_'*147)
        print("Spam Count:%s"% spam_count)
        print('_'*147)
        print("Ham Count:%s"% ham_count)
        print('_'*147)

Message: Okay name ur price as long as its legal! Wen can I pick them up? Y u ave x ams xx
 : ham
Message: I'm still looking for a car to buy. And have not gone 4the driving test yet.
 : ham
Message: As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune
 : ham
Message: wow. You're right! I didn't mean to do that. I guess once i gave up on boston men and changed my search location to nyc, something changed. Cuz on my signin page it still says boston.
 : ham
Message: Umma my life and vava umma love you lot dear
 : ham
Message: Thanks a lot for your wishes on my birthday. Thanks you for making my birthday truly memorable.
 : ham
Message: Aight, I'll hit you up when I get some cash
 : ham
Message: How would my ip address test that considering my computer isn't a minecraft server
 : ham
Message: I know! Grumpy old people. My mom was like you better not be lying. Then again I am always the one to play jokes...
 : ham
Message: Dont worry. I guess he's busy.
 : ham
Message: What is the plural of the noun research?
 : ham
Message: Going for dinner.msg you after.
 : ham
Message: I'm ok wif it cos i like 2 try new things. But i scared u dun like mah. Cos u said not too loud.
 : ham
Message: GENT! We are trying to contact you. Last weekends draw shows that you won a Œ£1000 prize GUARANTEED. Call 09064012160. Claim Code K52. Valid 12hrs only. 150ppm
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:1
___________________________________________________________________________________________________________________________________________________
Ham Count:13
___________________________________________________________________________________________________________________________________________________
Message: Wa, ur openin sentence very formal... Anyway, i'm fine too, juz tt i'm eatin too much n puttin on weight...Haha... So anythin special happened?
 : ham
Message: As I entered my cabin my PA said, '' Happy B'day Boss !!''. I felt special. She askd me 4 lunch. After lunch she invited me to her apartment. We went there.
 : ham
Message: You are a winner U have been specially selected 2 receive Œ£1000 or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810910p/min (18+)
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:2
___________________________________________________________________________________________________________________________________________________
Ham Count:15
___________________________________________________________________________________________________________________________________________________
Message: Goodo! Yes we must speak friday - egg-potato ratio for tortilla needed!
 : ham
Message: Hmm...my uncle just informed me that he's paying the school directly. So pls buy food.
 : ham
Message: PRIVATE! Your 2004 Account Statement for 07742676969 shows 786 unredeemed Bonus Points. To claim call 08719180248 Identifier Code: 45239 Expires
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:3
___________________________________________________________________________________________________________________________________________________
Ham Count:17
___________________________________________________________________________________________________________________________________________________
Message: URGENT! Your Mobile No. was awarded Œ£2000 Bonus Caller Prize on 5/9/03 This is our final try to contact U! Call from Landline 09064019788 BOX42WR29C, 150PPM
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:4
___________________________________________________________________________________________________________________________________________________
Ham Count:17
___________________________________________________________________________________________________________________________________________________
Message: here is my new address -apples&pairs&all that malarky
 : ham
Message: Todays Voda numbers ending 7548 are selected to receive a $350 award. If you have a match please call 08712300220 quoting claim code 4041 standard rates app
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:5
___________________________________________________________________________________________________________________________________________________
Ham Count:18
___________________________________________________________________________________________________________________________________________________
Message: I am going to sao mu today. Will be done only at 12
 : ham
Message: íì predict wat time í_'ll finish buying?
 : ham
Message: Good stuff, will do.
 : ham
Message: Just so that you know,yetunde hasn't sent money yet. I just sent her a text not to bother sending. So its over, you dont have to involve yourself in anything. I shouldn't have imposed anything on you in the first place so for that, i apologise.
 : ham
Message: Are you there in room.
 : ham
Message: HEY GIRL. HOW R U? HOPE U R WELL ME AN DEL R BAK! AGAIN LONG TIME NO C! GIVE ME A CALL SUM TIME FROM LUCYxx
 : ham
Message: K..k:)how much does it cost?
 : ham
Message: I'm home.
 : ham
Message: Dear, will call Tmorrow.pls accomodate.
 : ham
Message: First answer my question.
 : ham
Message: Sunshine Quiz Wkly Q! Win a top Sony DVD player if u know which country the Algarve is in? Txt ansr to 82277. Œ£1.50 SP:Tyrone
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:6
___________________________________________________________________________________________________________________________________________________
Ham Count:28
___________________________________________________________________________________________________________________________________________________
Message: Want 2 get laid tonight? Want real Dogging locations sent direct 2 ur mob? Join the UK's largest Dogging Network bt Txting GRAVEL to 69888! Nt. ec2a. 31p.msg@150p
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:7
___________________________________________________________________________________________________________________________________________________
Ham Count:28
___________________________________________________________________________________________________________________________________________________
Message: I only haf msn. It's yijue@hotmail.com
 : ham
Message: He is there. You call and meet him
 : ham
Message: No no. I will check all rooms befor activities
 : ham
Message: You'll not rcv any more msgs from the chat svc. For FREE Hardcore services text GO to: 69988 If u get nothing u must Age Verify with yr network & try again
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:8
___________________________________________________________________________________________________________________________________________________
Ham Count:31
___________________________________________________________________________________________________________________________________________________
Message: Got c... I lazy to type... I forgot í_ in lect... I saw a pouch but like not v nice...
 : ham
Message: K, text me when you're on the way
 : ham
Message: Sir, Waiting for your mail.
 : ham
Message: A swt thought: \Nver get tired of doing little things 4 lovable persons..\" Coz..somtimes those little things occupy d biggest part in their Hearts.. Gud ni8"
 : ham
Message: I know you are. Can you pls open the back?
 : ham
Message: Yes see ya not on the dot
 : ham
Message: Whats the staff name who is taking class for us?
 : ham
Message: FreeMsg Why haven't you replied to my text? I'm Randy, sexy, female and live local. Luv to hear from u. Netcollex Ltd 08700621170150p per msg reply Stop to end
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:9
___________________________________________________________________________________________________________________________________________________
Ham Count:38
___________________________________________________________________________________________________________________________________________________
Message: Ummma.will call after check in.our life will begin from qatar so pls pray very hard.
 : ham
Message: K..i deleted my contact that why?
 : ham
Message: Sindu got job in birla soft ..
 : ham
Message: The wine is flowing and i'm i have nevering..
 : ham
Message: Yup i thk cine is better cos no need 2 go down 2 plaza mah.
 : ham
Message: Ok... Ur typical reply...
 : ham
Message: As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune
 : ham
Message: You are everywhere dirt, on the floor, the windows, even on my shirt. And sometimes when i open my mouth, you are all that comes flowing out. I dream of my world without you, then half my chores are out too. A time of joy for me, lots of tv shows i.ll see. But i guess like all things you just must exist, like rain, hail and mist, and when my time here is done, you and i become one.
 : ham
Message: Aaooooright are you at work?
 : ham
Message: I'm leaving my house now...
 : ham
Message: Hello, my love. What are you doing? Did you get to that interview today? Are you you happy? Are you being a good boy? Do you think of me?Are you missing me ?
 : ham
Message: Customer service annoncement. You have a New Years delivery waiting for you. Please call 07046744435 now to arrange delivery
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:10
___________________________________________________________________________________________________________________________________________________
Ham Count:49
___________________________________________________________________________________________________________________________________________________
Message: You are a winner U have been specially selected 2 receive Œ£1000 cash or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810810
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:11
___________________________________________________________________________________________________________________________________________________
Ham Count:49
___________________________________________________________________________________________________________________________________________________
Message: Keep yourself safe for me because I need you and I miss you already and I envy everyone that see's you in real life
 : ham
Message: New car and house for my parents.:)i have only new job in hand:)
 : ham
Message: I'm so in love with you. I'm excited each day i spend with you. You make me so happy.
 : ham
Message: -PLS STOP bootydelious (32/F) is inviting you to be her friend. Reply YES-434 or NO-434 See her: www.SMS.ac/u/bootydelious STOP? Send STOP FRND to 62468
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:12
___________________________________________________________________________________________________________________________________________________
Ham Count:52
___________________________________________________________________________________________________________________________________________________
Message: BangBabes Ur order is on the way. U SHOULD receive a Service Msg 2 download UR content. If U do not, GoTo wap. bangb. tv on UR mobile internet/service menu
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:13
___________________________________________________________________________________________________________________________________________________
Ham Count:52
___________________________________________________________________________________________________________________________________________________
Message: I place all ur points on e cultures module already.
 : ham
Message: URGENT! We are trying to contact you. Last weekends draw shows that you have won a Œ£900 prize GUARANTEED. Call 09061701939. Claim code S89. Valid 12hrs only
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:14
___________________________________________________________________________________________________________________________________________________
Ham Count:53
___________________________________________________________________________________________________________________________________________________
Message: Hi frnd, which is best way to avoid missunderstding wit our beloved one's?
 : ham
Message: Great escape. I fancy the bridge but needs her lager. See you tomo
 : ham
Message: Yes :)it completely in out of form:)clark also utter waste.
 : ham
Message: Sir, I need AXIS BANK account no and bank address.
 : ham
Message: Hmmm.. Thk sure got time to hop ard... Ya, can go 4 free abt... Muz call u to discuss liao...
 : ham
Message: What time you coming down later?
 : ham
Message: Bloody hell, cant believe you forgot my surname Mr . Ill give u a clue, its spanish and begins with m...
 : ham
Message: Well, i'm gonna finish my bath now. Have a good...fine night.
 : ham
Message: Let me know when you've got the money so carlos can make the call
 : ham
Message: U still going to the mall?
 : ham
Message: Turns out my friends are staying for the whole show and won't be back til ~ &lt;#&gt; , so feel free to go ahead and smoke that $ &lt;#&gt;  worth
 : ham
Message: Text her. If she doesnt reply let me know so i can have her log in
 : ham
Message: Hi! You just spoke to MANEESHA V. We'd like to know if you were satisfied with the experience. Reply Toll Free with Yes or No.
 : ham
Message: You lifted my hopes with the offer of money. I am in need. Especially when the end of the month approaches and it hurts my studying. Anyways have a gr8 weekend
 : ham
Message: Lol no. U can trust me.
 : ham
Message: ok. I am a gentleman and will treat you with dignity and respect.
 : ham
Message: He will, you guys close?
 : ham
Message: Going on nothing great.bye
 : ham
Message: Hello handsome ! Are you finding that job ? Not being lazy ? Working towards getting back that net for mummy ? Where's my boytoy now ? Does he miss me ?
 : ham
Message: Haha awesome, be there in a minute
 : ham
Message: Please call our customer service representative on FREEPHONE 0808 145 4742 between 9am-11pm as you have WON a guaranteed Œ£1000 cash or Œ£5000 prize!
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:15
___________________________________________________________________________________________________________________________________________________
Ham Count:73
___________________________________________________________________________________________________________________________________________________
Message: Have you got Xmas radio times. If not i will get it now
 : ham
Message: I jus reached home. I go bathe first. But my sis using net tell u when she finishes k...
 : ham
Message: Are you unique enough? Find out from 30th August. www.areyouunique.co.uk
 : ham
Message: I'm sorry. I've joined the league of people that dont keep in touch. You mean a great deal to me. You have been a friend at all times even at great personal cost. Do have a great week.|
 : ham
Message: Hi :)finally i completed the course:)
 : ham
Message: It will stop on itself. I however suggest she stays with someone that will be able to give ors for every stool.
 : ham
Message: How are you doing? Hope you've settled in for the new school year. Just wishin you a gr8 day
 : ham
Message: Gud mrng dear hav a nice day
 : ham
Message: Did u got that persons story
 : ham
Message: is your hamster dead? Hey so tmr i meet you at 1pm orchard mrt?
 : ham
Message: Hi its Kate how is your evening? I hope i can see you tomorrow for a bit but i have to bloody babyjontet! Txt back if u can. :) xxx
 : ham
Message: Found it, ENC  &lt;#&gt; , where you at?
 : ham

In [35]:
import string 
import pandas as pd

from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.svm import (SVR,SVC)
from sklearn.tree import (DecisionTreeRegressor,DecisionTreeClassifier)
from sklearn.ensemble import (RandomForestRegressor,RandomForestClassifier)

from sklearn.model_selection import train_test_split
from sklearn.metrics import(
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

from matplotlib import style
import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")

In [43]:
spam_dataset=pd.read_csv("spam.csv", encoding="latin-1")

print("First 10 Elements of 'spam.csv':")
print('-'*63)
spam_dataset[:10]

First 10 Elements of 'spam.csv':
---------------------------------------------------------------

                                             Message Class
0  Go until jurong point, crazy.. Available only ...   ham
1                      Ok lar... Joking wif u oni...   ham
2  Free entry in 2 a wkly comp to win FA Cup fina...  spam
3  U dun say so early hor... U c already then say...   ham
4  Nah I don't think he goes to usf, he lives aro...   ham
5  FreeMsg Hey there darling it's been 3 week's n...  spam
6  Even my brother is not like to speak with me. ...   ham
7  As per your request 'Melle Melle (Oru Minnamin...   ham
8  WINNER!! As a valued network customer you have...  spam
9  Had your mobile 11 months or more? U R entitle...  spam

In [47]:
print("Last 10 Elements of 'spam.csv':")
print('-'*63)
spam_dataset[-10:]

Last 10 Elements of 'spam.csv':
---------------------------------------------------------------

                                                Message Class
5562  Ok lor... Sony ericsson salesman... I ask shuh...   ham
5563                                Ard 6 like dat lor.   ham
5564  Why don't you wait 'til at least wednesday to ...   ham
5565                                       Huh y lei...   ham
5566  REMINDER FROM O2: To get 2.50 pounds free call...  spam
5567  This is the 2nd time we have tried 2 contact u...  spam
5568              Will Ì_ b going to esplanade fr home?   ham
5569  Pity, * was in mood for that. So...any other s...   ham
5570  The guy did some bitching but I acted like i'd...   ham
5571                         Rofl. Its true to its name   ham

In [53]:
spam_dataset["Length"]=spam_dataset["Message"].apply(len)

print("First 10 Elements of 'spam.csv',with the column Length included:")
print('-'*73)
spam_dataset[:10]

First 10 Elements of 'spam.csv',with the column Length included:
-------------------------------------------------------------------------

                                             Message Class  Length
0  Go until jurong point, crazy.. Available only ...   ham     111
1                      Ok lar... Joking wif u oni...   ham      29
2  Free entry in 2 a wkly comp to win FA Cup fina...  spam     155
3  U dun say so early hor... U c already then say...   ham      49
4  Nah I don't think he goes to usf, he lives aro...   ham      61
5  FreeMsg Hey there darling it's been 3 week's n...  spam     148
6  Even my brother is not like to speak with me. ...   ham      77
7  As per your request 'Melle Melle (Oru Minnamin...   ham     160
8  WINNER!! As a valued network customer you have...  spam     158
9  Had your mobile 11 months or more? U R entitle...  spam     154

In [55]:
print("Last 10 Elements of 'spam.csv',with the column length included:")
print('-'*77)
spam_dataset[-10:]

Last 10 Elements of 'spam.csv',with the column length included:
-----------------------------------------------------------------------------

                                                Message Class  Length
5562  Ok lor... Sony ericsson salesman... I ask shuh...   ham      96
5563                                Ard 6 like dat lor.   ham      19
5564  Why don't you wait 'til at least wednesday to ...   ham      67
5565                                       Huh y lei...   ham      12
5566  REMINDER FROM O2: To get 2.50 pounds free call...  spam     147
5567  This is the 2nd time we have tried 2 contact u...  spam     161
5568              Will Ì_ b going to esplanade fr home?   ham      37
5569  Pity, * was in mood for that. So...any other s...   ham      57
5570  The guy did some bitching but I acted like i'd...   ham     125
5571                         Rofl. Its true to its name   ham      26

In [ ]:
def preprocess(spam_messages):
    messages=spam_messages.translate()