In [2]:
import nltk
import csv
import numpy as np
import codecs

In [3]:
def load_training_data():
    with open("Spam.csv", 'r', encoding="UTF-8", errors="ignore") as csvfile:
        reader = csv.reader(csvfile, delimiter=',', quotechar='"')
        total_list = []
        X = []
        Y = []

        for row in reader:
            # print(row)
            if row[1] == "neutral":
                continue
            else:
                # print(row[0])
                X.append(row[0])  # Message
                Y.append(row[1])  # Class
                total_list.append(row)

        classes = np.unique(Y)

        for each_class in classes:
            print(each_class)

        print((('-' * 33) + "\n") + "Length of Total List: ", len(total_list))

    return (total_list)


spam_ham = load_training_data()

Class
ham
spam
---------------------------------
Length of Total List:  5573

In [4]:
# Text Preprocessing(NLP)
messages=[]
for (words,category) in spam_ham:
    words_filtered=[e.lower() for e in words.split() if len(e)>=3]
    messages.append((words_filtered,category))

# Merge all words from messages into a single list
def get_words_in_messages(messages):
    all_words=[]

    for(words,category) in messages:
        all_words.extend(words)
    return all_words
    
# Collection of unique words
def get_word_features(wordlist):
    wordlist=nltk.FreqDist(wordlist) # Frequency
    word_features=wordlist.keys() # unique words

    return word_features

# Text Document into a feature Dictionary
def extract_features(document):
    document_words=set(document) # set for faster lookup ,remove duplicates and makes checking easier
    features={}

    for word in word_features:
        features["Contains:(%s)" % word]=(word in document_words) # create binary features(True/False)
    return features

word_features=get_word_features(get_words_in_messages(messages))
training_set=nltk.classify.apply_features(extract_features,messages)
classifier=nltk.NaiveBayesClassifier.train(training_set)

In [5]:
print("RESULTS".center(90, '_') + "\n" +
      "Accuracy:" + "\t" + f"{(nltk.classify.util.accuracy(classifier, training_set)) * 100}%", end="\n\n")
classifier.show_most_informative_features(20)

print('_' * 90)

_________________________________________RESULTS__________________________________________
Accuracy:	99.1925354387224%

Most Informative Features
          Contains:(100) = True             spam : ham    =    161.3 : 1.0
       Contains:(latest) = True             spam : ham    =    148.4 : 1.0
      Contains:(message) = True            Class : ham    =     96.5 : 1.0
         Contains:(2000) = True             spam : ham    =     92.5 : 1.0
        Contains:(nokia) = True             spam : ham    =     91.2 : 1.0
        Contains:(await) = True             spam : ham    =     83.9 : 1.0
         Contains:(now!) = True             spam : ham    =     82.7 : 1.0
      Contains:(service) = True             spam : ham    =     69.5 : 1.0
        Contains:(video) = True             spam : ham    =     68.4 : 1.0
          Contains:(txt) = True             spam : ham    =     66.8 : 1.0
         Contains:(code) = True             spam : ham    =     66.7 : 1.0
     Contains:(selected) = True             spam : ham    =     65.8 : 1.0
      Contains:(network) = True             spam : ham    =     60.6 : 1.0
     Contains:(services) = True             spam : ham    =     58.1 : 1.0
      Contains:(attempt) = True             spam : ham    =     55.5 : 1.0
       Contains:(orange) = True             spam : ham    =     55.5 : 1.0
       Contains:(caller) = True             spam : ham    =     53.8 : 1.0
Contains:(congratulations) = True             spam : ham    =     53.8 : 1.0
       Contains:(player) = True             spam : ham    =     53.8 : 1.0
      Contains:(voucher) = True             spam : ham    =     53.8 : 1.0
__________________________________________________________________________________________

In [6]:
# Read and store test text
def load_test_data():
    test_messages=[]
    test=codecs.open("Spamtest.txt",'r',"UTF-8")

    for each_value in test:
        test_messages.append(each_value)
    return test_messages

In [7]:
# Load test file containing message only
run_messages=load_test_data()
spam_count=0
ham_count=0

for each_messages in run_messages:
    values=classifier.classify(extract_features(each_messages.split()))


    print("Message:",each_messages,":",values)

    if values=="ham":
        ham_count+=1
    else:
        spam_count+=1

        print('_'*147)
        print("Spam Count:%s"% spam_count)
        print('_'*147)
        print("Ham Count:%s"% ham_count)
        print('_'*147)

Message: Okay name ur price as long as its legal! Wen can I pick them up? Y u ave x ams xx
 : ham
Message: I'm still looking for a car to buy. And have not gone 4the driving test yet.
 : ham
Message: As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune
 : ham
Message: wow. You're right! I didn't mean to do that. I guess once i gave up on boston men and changed my search location to nyc, something changed. Cuz on my signin page it still says boston.
 : ham
Message: Umma my life and vava umma love you lot dear
 : ham
Message: Thanks a lot for your wishes on my birthday. Thanks you for making my birthday truly memorable.
 : ham
Message: Aight, I'll hit you up when I get some cash
 : ham
Message: How would my ip address test that considering my computer isn't a minecraft server
 : ham
Message: I know! Grumpy old people. My mom was like you better not be lying. Then again I am always the one to play jokes...
 : ham
Message: Dont worry. I guess he's busy.
 : ham
Message: What is the plural of the noun research?
 : ham
Message: Going for dinner.msg you after.
 : ham
Message: I'm ok wif it cos i like 2 try new things. But i scared u dun like mah. Cos u said not too loud.
 : ham
Message: GENT! We are trying to contact you. Last weekends draw shows that you won a Œ£1000 prize GUARANTEED. Call 09064012160. Claim Code K52. Valid 12hrs only. 150ppm
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:1
___________________________________________________________________________________________________________________________________________________
Ham Count:13
___________________________________________________________________________________________________________________________________________________
Message: Wa, ur openin sentence very formal... Anyway, i'm fine too, juz tt i'm eatin too much n puttin on weight...Haha... So anythin special happened?
 : ham
Message: As I entered my cabin my PA said, '' Happy B'day Boss !!''. I felt special. She askd me 4 lunch. After lunch she invited me to her apartment. We went there.
 : ham
Message: You are a winner U have been specially selected 2 receive Œ£1000 or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810910p/min (18+)
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:2
___________________________________________________________________________________________________________________________________________________
Ham Count:15
___________________________________________________________________________________________________________________________________________________
Message: Goodo! Yes we must speak friday - egg-potato ratio for tortilla needed!
 : ham
Message: Hmm...my uncle just informed me that he's paying the school directly. So pls buy food.
 : ham
Message: PRIVATE! Your 2004 Account Statement for 07742676969 shows 786 unredeemed Bonus Points. To claim call 08719180248 Identifier Code: 45239 Expires
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:3
___________________________________________________________________________________________________________________________________________________
Ham Count:17
___________________________________________________________________________________________________________________________________________________
Message: URGENT! Your Mobile No. was awarded Œ£2000 Bonus Caller Prize on 5/9/03 This is our final try to contact U! Call from Landline 09064019788 BOX42WR29C, 150PPM
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:4
___________________________________________________________________________________________________________________________________________________
Ham Count:17
___________________________________________________________________________________________________________________________________________________
Message: here is my new address -apples&pairs&all that malarky
 : ham
Message: Todays Voda numbers ending 7548 are selected to receive a $350 award. If you have a match please call 08712300220 quoting claim code 4041 standard rates app
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:5
___________________________________________________________________________________________________________________________________________________
Ham Count:18
___________________________________________________________________________________________________________________________________________________
Message: I am going to sao mu today. Will be done only at 12
 : ham
Message: íì predict wat time í_'ll finish buying?
 : ham
Message: Good stuff, will do.
 : ham
Message: Just so that you know,yetunde hasn't sent money yet. I just sent her a text not to bother sending. So its over, you dont have to involve yourself in anything. I shouldn't have imposed anything on you in the first place so for that, i apologise.
 : ham
Message: Are you there in room.
 : ham
Message: HEY GIRL. HOW R U? HOPE U R WELL ME AN DEL R BAK! AGAIN LONG TIME NO C! GIVE ME A CALL SUM TIME FROM LUCYxx
 : ham
Message: K..k:)how much does it cost?
 : ham
Message: I'm home.
 : ham
Message: Dear, will call Tmorrow.pls accomodate.
 : ham
Message: First answer my question.
 : ham
Message: Sunshine Quiz Wkly Q! Win a top Sony DVD player if u know which country the Algarve is in? Txt ansr to 82277. Œ£1.50 SP:Tyrone
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:6
___________________________________________________________________________________________________________________________________________________
Ham Count:28
___________________________________________________________________________________________________________________________________________________
Message: Want 2 get laid tonight? Want real Dogging locations sent direct 2 ur mob? Join the UK's largest Dogging Network bt Txting GRAVEL to 69888! Nt. ec2a. 31p.msg@150p
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:7
___________________________________________________________________________________________________________________________________________________
Ham Count:28
___________________________________________________________________________________________________________________________________________________
Message: I only haf msn. It's yijue@hotmail.com
 : ham
Message: He is there. You call and meet him
 : ham
Message: No no. I will check all rooms befor activities
 : ham
Message: You'll not rcv any more msgs from the chat svc. For FREE Hardcore services text GO to: 69988 If u get nothing u must Age Verify with yr network & try again
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:8
___________________________________________________________________________________________________________________________________________________
Ham Count:31
___________________________________________________________________________________________________________________________________________________
Message: Got c... I lazy to type... I forgot í_ in lect... I saw a pouch but like not v nice...
 : ham
Message: K, text me when you're on the way
 : ham
Message: Sir, Waiting for your mail.
 : ham
Message: A swt thought: \Nver get tired of doing little things 4 lovable persons..\" Coz..somtimes those little things occupy d biggest part in their Hearts.. Gud ni8"
 : ham
Message: I know you are. Can you pls open the back?
 : ham
Message: Yes see ya not on the dot
 : ham
Message: Whats the staff name who is taking class for us?
 : ham
Message: FreeMsg Why haven't you replied to my text? I'm Randy, sexy, female and live local. Luv to hear from u. Netcollex Ltd 08700621170150p per msg reply Stop to end
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:9
___________________________________________________________________________________________________________________________________________________
Ham Count:38
___________________________________________________________________________________________________________________________________________________
Message: Ummma.will call after check in.our life will begin from qatar so pls pray very hard.
 : ham
Message: K..i deleted my contact that why?
 : ham
Message: Sindu got job in birla soft ..
 : ham
Message: The wine is flowing and i'm i have nevering..
 : ham
Message: Yup i thk cine is better cos no need 2 go down 2 plaza mah.
 : ham
Message: Ok... Ur typical reply...
 : ham
Message: As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune
 : ham
Message: You are everywhere dirt, on the floor, the windows, even on my shirt. And sometimes when i open my mouth, you are all that comes flowing out. I dream of my world without you, then half my chores are out too. A time of joy for me, lots of tv shows i.ll see. But i guess like all things you just must exist, like rain, hail and mist, and when my time here is done, you and i become one.
 : ham
Message: Aaooooright are you at work?
 : ham
Message: I'm leaving my house now...
 : ham
Message: Hello, my love. What are you doing? Did you get to that interview today? Are you you happy? Are you being a good boy? Do you think of me?Are you missing me ?
 : ham
Message: Customer service annoncement. You have a New Years delivery waiting for you. Please call 07046744435 now to arrange delivery
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:10
___________________________________________________________________________________________________________________________________________________
Ham Count:49
___________________________________________________________________________________________________________________________________________________
Message: You are a winner U have been specially selected 2 receive Œ£1000 cash or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810810
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:11
___________________________________________________________________________________________________________________________________________________
Ham Count:49
___________________________________________________________________________________________________________________________________________________
Message: Keep yourself safe for me because I need you and I miss you already and I envy everyone that see's you in real life
 : ham
Message: New car and house for my parents.:)i have only new job in hand:)
 : ham
Message: I'm so in love with you. I'm excited each day i spend with you. You make me so happy.
 : ham
Message: -PLS STOP bootydelious (32/F) is inviting you to be her friend. Reply YES-434 or NO-434 See her: www.SMS.ac/u/bootydelious STOP? Send STOP FRND to 62468
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:12
___________________________________________________________________________________________________________________________________________________
Ham Count:52
___________________________________________________________________________________________________________________________________________________
Message: BangBabes Ur order is on the way. U SHOULD receive a Service Msg 2 download UR content. If U do not, GoTo wap. bangb. tv on UR mobile internet/service menu
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:13
___________________________________________________________________________________________________________________________________________________
Ham Count:52
___________________________________________________________________________________________________________________________________________________
Message: I place all ur points on e cultures module already.
 : ham
Message: URGENT! We are trying to contact you. Last weekends draw shows that you have won a Œ£900 prize GUARANTEED. Call 09061701939. Claim code S89. Valid 12hrs only
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:14
___________________________________________________________________________________________________________________________________________________
Ham Count:53
___________________________________________________________________________________________________________________________________________________
Message: Hi frnd, which is best way to avoid missunderstding wit our beloved one's?
 : ham
Message: Great escape. I fancy the bridge but needs her lager. See you tomo
 : ham
Message: Yes :)it completely in out of form:)clark also utter waste.
 : ham
Message: Sir, I need AXIS BANK account no and bank address.
 : ham
Message: Hmmm.. Thk sure got time to hop ard... Ya, can go 4 free abt... Muz call u to discuss liao...
 : ham
Message: What time you coming down later?
 : ham
Message: Bloody hell, cant believe you forgot my surname Mr . Ill give u a clue, its spanish and begins with m...
 : ham
Message: Well, i'm gonna finish my bath now. Have a good...fine night.
 : ham
Message: Let me know when you've got the money so carlos can make the call
 : ham
Message: U still going to the mall?
 : ham
Message: Turns out my friends are staying for the whole show and won't be back til ~ &lt;#&gt; , so feel free to go ahead and smoke that $ &lt;#&gt;  worth
 : ham
Message: Text her. If she doesnt reply let me know so i can have her log in
 : ham
Message: Hi! You just spoke to MANEESHA V. We'd like to know if you were satisfied with the experience. Reply Toll Free with Yes or No.
 : ham
Message: You lifted my hopes with the offer of money. I am in need. Especially when the end of the month approaches and it hurts my studying. Anyways have a gr8 weekend
 : ham
Message: Lol no. U can trust me.
 : ham
Message: ok. I am a gentleman and will treat you with dignity and respect.
 : ham
Message: He will, you guys close?
 : ham
Message: Going on nothing great.bye
 : ham
Message: Hello handsome ! Are you finding that job ? Not being lazy ? Working towards getting back that net for mummy ? Where's my boytoy now ? Does he miss me ?
 : ham
Message: Haha awesome, be there in a minute
 : ham
Message: Please call our customer service representative on FREEPHONE 0808 145 4742 between 9am-11pm as you have WON a guaranteed Œ£1000 cash or Œ£5000 prize!
 : spam
___________________________________________________________________________________________________________________________________________________
Spam Count:15
___________________________________________________________________________________________________________________________________________________
Ham Count:73
___________________________________________________________________________________________________________________________________________________
Message: Have you got Xmas radio times. If not i will get it now
 : ham
Message: I jus reached home. I go bathe first. But my sis using net tell u when she finishes k...
 : ham
Message: Are you unique enough? Find out from 30th August. www.areyouunique.co.uk
 : ham
Message: I'm sorry. I've joined the league of people that dont keep in touch. You mean a great deal to me. You have been a friend at all times even at great personal cost. Do have a great week.|
 : ham
Message: Hi :)finally i completed the course:)
 : ham
Message: It will stop on itself. I however suggest she stays with someone that will be able to give ors for every stool.
 : ham
Message: How are you doing? Hope you've settled in for the new school year. Just wishin you a gr8 day
 : ham
Message: Gud mrng dear hav a nice day
 : ham
Message: Did u got that persons story
 : ham
Message: is your hamster dead? Hey so tmr i meet you at 1pm orchard mrt?
 : ham
Message: Hi its Kate how is your evening? I hope i can see you tomorrow for a bit but i have to bloody babyjontet! Txt back if u can. :) xxx
 : ham
Message: Found it, ENC  &lt;#&gt; , where you at?
 : ham

In [8]:
import string 
import pandas as pd

from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.svm import (SVR,SVC)
from sklearn.tree import (DecisionTreeRegressor,DecisionTreeClassifier)
from sklearn.ensemble import (RandomForestRegressor,RandomForestClassifier)

from sklearn.model_selection import train_test_split
from sklearn.metrics import(
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

from matplotlib import style
import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")

In [9]:
spam_dataset=pd.read_csv("spam.csv", encoding="latin-1")

print("First 10 Elements of 'spam.csv':")
print('-'*63)
spam_dataset[:10]

First 10 Elements of 'spam.csv':
---------------------------------------------------------------

                                             Message Class
0  Go until jurong point, crazy.. Available only ...   ham
1                      Ok lar... Joking wif u oni...   ham
2  Free entry in 2 a wkly comp to win FA Cup fina...  spam
3  U dun say so early hor... U c already then say...   ham
4  Nah I don't think he goes to usf, he lives aro...   ham
5  FreeMsg Hey there darling it's been 3 week's n...  spam
6  Even my brother is not like to speak with me. ...   ham
7  As per your request 'Melle Melle (Oru Minnamin...   ham
8  WINNER!! As a valued network customer you have...  spam
9  Had your mobile 11 months or more? U R entitle...  spam

In [10]:
print("Last 10 Elements of 'spam.csv':")
print('-'*63)
spam_dataset[-10:]

Last 10 Elements of 'spam.csv':
---------------------------------------------------------------

                                                Message Class
5562  Ok lor... Sony ericsson salesman... I ask shuh...   ham
5563                                Ard 6 like dat lor.   ham
5564  Why don't you wait 'til at least wednesday to ...   ham
5565                                       Huh y lei...   ham
5566  REMINDER FROM O2: To get 2.50 pounds free call...  spam
5567  This is the 2nd time we have tried 2 contact u...  spam
5568              Will Ì_ b going to esplanade fr home?   ham
5569  Pity, * was in mood for that. So...any other s...   ham
5570  The guy did some bitching but I acted like i'd...   ham
5571                         Rofl. Its true to its name   ham

In [11]:
spam_dataset["Length"]=spam_dataset["Message"].apply(len)

print("First 10 Elements of 'spam.csv',with the column Length included:")
print('-'*73)
spam_dataset[:10]

First 10 Elements of 'spam.csv',with the column Length included:
-------------------------------------------------------------------------

                                             Message Class  Length
0  Go until jurong point, crazy.. Available only ...   ham     111
1                      Ok lar... Joking wif u oni...   ham      29
2  Free entry in 2 a wkly comp to win FA Cup fina...  spam     155
3  U dun say so early hor... U c already then say...   ham      49
4  Nah I don't think he goes to usf, he lives aro...   ham      61
5  FreeMsg Hey there darling it's been 3 week's n...  spam     148
6  Even my brother is not like to speak with me. ...   ham      77
7  As per your request 'Melle Melle (Oru Minnamin...   ham     160
8  WINNER!! As a valued network customer you have...  spam     158
9  Had your mobile 11 months or more? U R entitle...  spam     154

In [12]:
print("Last 10 Elements of 'spam.csv',with the column length included:")
print('-'*77)
spam_dataset[-10:]

Last 10 Elements of 'spam.csv',with the column length included:
-----------------------------------------------------------------------------

                                                Message Class  Length
5562  Ok lor... Sony ericsson salesman... I ask shuh...   ham      96
5563                                Ard 6 like dat lor.   ham      19
5564  Why don't you wait 'til at least wednesday to ...   ham      67
5565                                       Huh y lei...   ham      12
5566  REMINDER FROM O2: To get 2.50 pounds free call...  spam     147
5567  This is the 2nd time we have tried 2 contact u...  spam     161
5568              Will Ì_ b going to esplanade fr home?   ham      37
5569  Pity, * was in mood for that. So...any other s...   ham      57
5570  The guy did some bitching but I acted like i'd...   ham     125
5571                         Rofl. Its true to its name   ham      26

In [13]:
# Removing stop words and punctuation
def preprocess(spam_messages):
    messages=spam_messages.translate(str.maketrans('','',string.punctuation))
    messages=[word for word in messages.split() if word.lower() not in stopwords.words("english")]
    spam_words=''

    print(messages)


# Stemming 
    for message in messages:
        stemmer=SnowballStemmer("english")
        spam_words +=(stemmer.stem(message)) + " "

    return spam_words

text_features=spam_dataset["Message"].copy()
text_features=text_features.apply(preprocess)

['Go', 'jurong', 'point', 'crazy', 'Available', 'bugis', 'n', 'great', 'world', 'la', 'e', 'buffet', 'Cine', 'got', 'amore', 'wat']
['Ok', 'lar', 'Joking', 'wif', 'u', 'oni']
['Free', 'entry', '2', 'wkly', 'comp', 'win', 'FA', 'Cup', 'final', 'tkts', '21st', 'May', '2005', 'Text', 'FA', '87121', 'receive', 'entry', 'questionstd', 'txt', 'rateTCs', 'apply', '08452810075over18s']
['U', 'dun', 'say', 'early', 'hor', 'U', 'c', 'already', 'say']
['Nah', 'dont', 'think', 'goes', 'usf', 'lives', 'around', 'though']
['FreeMsg', 'Hey', 'darling', '3', 'weeks', 'word', 'back', 'Id', 'like', 'fun', 'still', 'Tb', 'ok', 'XxX', 'std', 'chgs', 'send', 'å£150', 'rcv']
['Even', 'brother', 'like', 'speak', 'treat', 'like', 'aids', 'patent']
['per', 'request', 'Melle', 'Melle', 'Oru', 'Minnaminunginte', 'Nurungu', 'Vettam', 'set', 'callertune', 'Callers', 'Press', '9', 'copy', 'friends', 'Callertune']
['WINNER', 'valued', 'network', 'customer', 'selected', 'receivea', 'å£900', 'prize', 'reward', 'claim', 'call', '09061701461', 'Claim', 'code', 'KL341', 'Valid', '12', 'hours']
['mobile', '11', 'months', 'U', 'R', 'entitled', 'Update', 'latest', 'colour', 'mobiles', 'camera', 'Free', 'Call', 'Mobile', 'Update', 'Co', 'FREE', '08002986030']
['Im', 'gonna', 'home', 'soon', 'dont', 'want', 'talk', 'stuff', 'anymore', 'tonight', 'k', 'Ive', 'cried', 'enough', 'today']
['SIX', 'chances', 'win', 'CASH', '100', '20000', 'pounds', 'txt', 'CSH11', 'send', '87575', 'Cost', '150pday', '6days', '16', 'TsandCs', 'apply', 'Reply', 'HL', '4', 'info']
['URGENT', '1', 'week', 'FREE', 'membership', 'å£100000', 'Prize', 'Jackpot', 'Txt', 'word', 'CLAIM', '81010', 'TC', 'wwwdbuknet', 'LCCLTD', 'POBOX', '4403LDNW1A7RW18']
['Ive', 'searching', 'right', 'words', 'thank', 'breather', 'promise', 'wont', 'take', 'help', 'granted', 'fulfil', 'promise', 'wonderful', 'blessing', 'times']
['DATE', 'SUNDAY']
['XXXMobileMovieClub', 'use', 'credit', 'click', 'WAP', 'link', 'next', 'txt', 'message', 'click', 'httpwap', 'xxxmobilemovieclubcomnQJKGIGHJJGCBL']
['Oh', 'kim', 'watching']
['Eh', 'u', 'remember', '2', 'spell', 'name', 'Yes', 'v', 'naughty', 'make', 'v', 'wet']
['Fine', 'thatåÕs', 'way', 'u', 'feel', 'ThatåÕs', 'way', 'gota', 'b']
['England', 'v', 'Macedonia', 'dont', 'miss', 'goalsteam', 'news', 'Txt', 'ur', 'national', 'team', '87077', 'eg', 'ENGLAND', '87077', 'TryWALES', 'SCOTLAND', '4txtÌ¼120', 'POBOXox36504W45WQ', '16']
['seriously', 'spell', 'name']
['I\x89Û÷m', 'going', 'try', '2', 'months', 'ha', 'ha', 'joking']
['Ì', 'pay', 'first', 'lar', 'da', 'stock', 'comin']
['Aft', 'finish', 'lunch', 'go', 'str', 'lor', 'Ard', '3', 'smth', 'lor', 'U', 'finish', 'ur', 'lunch', 'already']
['Ffffffffff', 'Alright', 'way', 'meet', 'sooner']
['forced', 'eat', 'slice', 'Im', 'really', 'hungry', 'tho', 'sucks', 'Mark', 'getting', 'worried', 'knows', 'Im', 'sick', 'turn', 'pizza', 'Lol']
['Lol', 'always', 'convincing']
['catch', 'bus', 'frying', 'egg', 'make', 'tea', 'eating', 'moms', 'left', 'dinner', 'feel', 'Love']
['Im', 'back', 'amp', 'packing', 'car', 'Ill', 'let', 'know', 'theres', 'room']
['Ahhh', 'Work', 'vaguely', 'remember', 'feel', 'like', 'Lol']
['Wait', 'thats', 'still', 'clear', 'sure', 'sarcastic', 'thats', 'x', 'doesnt', 'want', 'live', 'us']
['Yeah', 'got', '2', 'v', 'apologetic', 'n', 'fallen', 'actin', 'like', 'spoilt', 'child', 'got', 'caught', 'Till', '2', 'wont', 'go', 'badly', 'cheers']
['K', 'tell', 'anything']
['fear', 'fainting', 'housework', 'Quick', 'cuppa']
['Thanks', 'subscription', 'Ringtone', 'UK', 'mobile', 'charged', 'å£5month', 'Please', 'confirm', 'replying', 'YES', 'reply', 'charged']
['Yup', 'Ok', 'go', 'home', 'look', 'timings', 'msg', 'Ì', 'Xuhui', 'going', 'learn', '2nd', 'may', 'lesson', '8am']
['Oops', 'Ill', 'let', 'know', 'roommates', 'done']
['see', 'letter', 'B', 'car']
['Anything', 'lor', 'U', 'decide']
['Hello', 'Hows', 'saturday', 'go', 'texting', 'see', 'youd', 'decided', 'anything', 'tomo', 'im', 'trying', 'invite', 'anything']
['Pls', 'go', 'ahead', 'watts', 'wanted', 'sure', 'great', 'weekend', 'Abiola']
['forget', 'tell', 'want', 'need', 'crave', 'love', 'sweet', 'Arabian', 'steed', 'Mmmmmm', 'Yummy']
['07732584351', 'Rodger', 'Burns', 'MSG', 'tried', 'call', 'reply', 'sms', 'free', 'nokia', 'mobile', 'free', 'camcorder', 'Please', 'call', '08000930705', 'delivery', 'tomorrow']
['SEEING']
['Great', 'hope', 'like', 'man', 'well', 'endowed', 'ltgt', 'inches']
['callsmessagesmissed', 'calls']
['Didnt', 'get', 'hep', 'b', 'immunisation', 'nigeria']
['Fair', 'enough', 'anything', 'going']
['Yeah', 'hopefully', 'tyler', 'cant', 'could', 'maybe', 'ask', 'around', 'bit']
['U', 'dont', 'know', 'stubborn', 'didnt', 'even', 'want', 'go', 'hospital', 'kept', 'telling', 'Mark', 'Im', 'weak', 'sucker', 'Hospitals', 'weak', 'suckers']
['thinked', 'First', 'time', 'saw', 'class']
['gram', 'usually', 'runs', 'like', 'ltgt', 'half', 'eighth', 'smarter', 'though', 'gets', 'almost', 'whole', 'second', 'gram', 'ltgt']
['K', 'fyi', 'x', 'ride', 'early', 'tomorrow', 'morning', 'hes', 'crashing', 'place', 'tonight']
['Wow', 'never', 'realized', 'embarassed', 'accomodations', 'thought', 'liked', 'since', 'best', 'could', 'always', 'seemed', 'happy', 'cave', 'Im', 'sorry', 'didnt', 'dont', 'give', 'Im', 'sorry', 'offered', 'Im', 'sorry', 'room', 'embarassing']
['SMS', 'ac', 'Sptv', 'New', 'Jersey', 'Devils', 'Detroit', 'Red', 'Wings', 'play', 'Ice', 'Hockey', 'Correct', 'Incorrect', 'End', 'Reply', 'END', 'SPTV']
['know', 'Mallika', 'Sherawat', 'yesterday', 'Find', 'ltURLgt']
['Congrats', '1', 'year', 'special', 'cinema', 'pass', '2', 'call', '09061209465', 'C', 'Suprman', 'V', 'Matrix3', 'StarWars3', 'etc', '4', 'FREE', 'bx420ip45we', '150pm', 'Dont', 'miss']
['Sorry', 'Ill', 'call', 'later', 'meeting']
['Tell', 'reached']
['Yesgauti', 'sehwag', 'odi', 'series']
['gonna', 'pick', '1', 'burger', 'way', 'home', 'cant', 'even', 'move', 'Pain', 'killing']
['Ha', 'ha', 'ha', 'good', 'joke', 'Girls', 'situation', 'seekers']
['part', 'checking', 'IQ']
['Sorry', 'roommates', 'took', 'forever', 'ok', 'come']
['Ok', 'lar', 'double', 'check', 'wif', 'da', 'hair', 'dresser', 'already', 'said', 'wun', 'cut', 'v', 'short', 'said', 'cut', 'look', 'nice']
['valued', 'customer', 'pleased', 'advise', 'following', 'recent', 'review', 'Mob', 'awarded', 'å£1500', 'Bonus', 'Prize', 'call', '09066364589']
['Today', 'song', 'dedicated', 'day', 'song', 'u', 'dedicate', 'Send', 'ur', 'valuable', 'frnds', 'first', 'rply']
['Urgent', 'UR', 'awarded', 'complimentary', 'trip', 'EuroDisinc', 'Trav', 'AcoEntry41', 'å£1000', 'claim', 'txt', 'DIS', '87121', '186å£150moreFrmMob', 'ShrAcomOrSglSuplt10', 'LS1', '3AJ']
['hear', 'new', 'Divorce', 'Barbie', 'comes', 'Kens', 'stuff']
['plane', 'give', 'month', 'end']
['Wah', 'lucky', 'man', 'save', 'money', 'Hee']
['Finished', 'class']
['HI', 'BABE', 'IM', 'HOME', 'WANNA', 'SOMETHING', 'XX']
['Kkwhere', 'youhow', 'performed']
['U', 'call']
['waiting', 'machan', 'Call', 'free']
['Thats', 'cool', 'gentleman', 'treat', 'dignity', 'respect']
['like', 'peoples', 'much', 'shy', 'pa']
['operate', 'ltgt']
['Still', 'looking', 'job', 'much', 'Tas', 'earn']
['Sorry', 'Ill', 'call', 'later']
['K', 'call', 'ah']
['Ok', 'way', 'home', 'hi', 'hi']
['place', 'man']
['Yup', 'next', 'stop']
['call', 'later', 'dont', 'network', 'urgnt', 'sms']
['real', 'u', 'getting', 'yo', 'need', '2', 'tickets', 'one', 'jacket', 'Im', 'done', 'already', 'used', 'multis']
['Yes', 'started', 'send', 'requests', 'make', 'pain', 'came', 'back', 'Im', 'back', 'bed', 'Double', 'coins', 'factory', 'gotta', 'cash', 'nitros']
['Im', 'really', 'still', 'tonight', 'babe']
['Ela', 'kanoil', 'download', 'come', 'wen', 'ur', 'free']
['Yeah', 'Don\x89Û÷t', 'stand', 'close', 'tho', 'you\x89Û÷ll', 'catch', 'something']
['Sorry', 'pain', 'ok', 'meet', 'another', 'night', 'spent', 'late', 'afternoon', 'casualty', 'means', 'havent', 'done', 'stuff42moro', 'includes', 'time', 'sheets', 'Sorry']
['Smile', 'Pleasure', 'Smile', 'Pain', 'Smile', 'trouble', 'pours', 'like', 'Rain', 'Smile', 'sum1', 'Hurts', 'U', 'Smile', 'becoz', 'SOMEONE', 'still', 'Loves', 'see', 'u', 'Smiling']
['Please', 'call', 'customer', 'service', 'representative', '0800', '169', '6031', '10am9pm', 'guaranteed', 'å£1000', 'cash', 'å£5000', 'prize']
['Havent', 'planning', 'buy', 'later', 'check', 'already', 'lido', 'got', '530', 'show', 'e', 'afternoon', 'U', 'finish', 'work', 'already']
['free', 'ringtone', 'waiting', 'collected', 'Simply', 'text', 'password', 'MIX', '85069', 'verify', 'Get', 'Usher', 'Britney', 'FML']
['Watching', 'telugu', 'moviewat', 'abt', 'u']
['see', 'finish', 'loads', 'loans', 'pay']
['Hi', 'Wk', 'ok', 'hols', 'Yes', 'bit', 'run', 'Forgot', 'hairdressers', 'appointment', 'four', 'need', 'get', 'home', 'n', 'shower', 'beforehand', 'cause', 'prob', 'u', 'ham']
['Please', 'dont', 'text', 'anymore', 'nothing', 'else', 'say']
['Okay', 'name', 'ur', 'price', 'long', 'legal', 'Wen', 'pick', 'u', 'ave', 'x', 'ams', 'xx']
['Im', 'still', 'looking', 'car', 'buy', 'gone', '4the', 'driving', 'test', 'yet']
['per', 'request', 'Melle', 'Melle', 'Oru', 'Minnaminunginte', 'Nurungu', 'Vettam', 'set', 'callertune', 'Callers', 'Press', '9', 'copy', 'friends', 'Callertune']
['wow', 'Youre', 'right', 'didnt', 'mean', 'guess', 'gave', 'boston', 'men', 'changed', 'search', 'location', 'nyc', 'something', 'changed', 'Cuz', 'signin', 'page', 'still', 'says', 'boston']
['Umma', 'life', 'vava', 'umma', 'love', 'lot', 'dear']
['Thanks', 'lot', 'wishes', 'birthday', 'Thanks', 'making', 'birthday', 'truly', 'memorable']
['Aight', 'Ill', 'hit', 'get', 'cash']
['would', 'ip', 'address', 'test', 'considering', 'computer', 'isnt', 'minecraft', 'server']
['know', 'Grumpy', 'old', 'people', 'mom', 'like', 'better', 'lying', 'always', 'one', 'play', 'jokes']
['Dont', 'worry', 'guess', 'hes', 'busy']
['plural', 'noun', 'research']
['Going', 'dinnermsg']
['Im', 'ok', 'wif', 'cos', 'like', '2', 'try', 'new', 'things', 'scared', 'u', 'dun', 'like', 'mah', 'Cos', 'u', 'said', 'loud']
['GENT', 'trying', 'contact', 'Last', 'weekends', 'draw', 'shows', 'å£1000', 'prize', 'GUARANTEED', 'Call', '09064012160', 'Claim', 'Code', 'K52', 'Valid', '12hrs', '150ppm']
['Wa', 'ur', 'openin', 'sentence', 'formal', 'Anyway', 'im', 'fine', 'juz', 'tt', 'im', 'eatin', 'much', 'n', 'puttin', 'weightHaha', 'anythin', 'special', 'happened']
['entered', 'cabin', 'PA', 'said', 'Happy', 'Bday', 'Boss', 'felt', 'special', 'askd', '4', 'lunch', 'lunch', 'invited', 'apartment', 'went']
['winner', 'U', 'specially', 'selected', '2', 'receive', 'å£1000', '4', 'holiday', 'flights', 'inc', 'speak', 'live', 'operator', '2', 'claim', '0871277810910pmin', '18']
['Goodo', 'Yes', 'must', 'speak', 'friday', 'eggpotato', 'ratio', 'tortilla', 'needed']
['Hmmmy', 'uncle', 'informed', 'hes', 'paying', 'school', 'directly', 'pls', 'buy', 'food']
['PRIVATE', '2004', 'Account', 'Statement', '07742676969', 'shows', '786', 'unredeemed', 'Bonus', 'Points', 'claim', 'call', '08719180248', 'Identifier', 'Code', '45239', 'Expires']
['URGENT', 'Mobile', 'awarded', 'å£2000', 'Bonus', 'Caller', 'Prize', '5903', 'final', 'try', 'contact', 'U', 'Call', 'Landline', '09064019788', 'BOX42WR29C', '150PPM']
['new', 'address', 'applespairsall', 'malarky']
['Todays', 'Voda', 'numbers', 'ending', '7548', 'selected', 'receive', '350', 'award', 'match', 'please', 'call', '08712300220', 'quoting', 'claim', 'code', '4041', 'standard', 'rates', 'app']
['going', 'sao', 'mu', 'today', 'done', '12']
['ÌÏ', 'predict', 'wat', 'time', 'Ìll', 'finish', 'buying']
['Good', 'stuff']
['knowyetunde', 'hasnt', 'sent', 'money', 'yet', 'sent', 'text', 'bother', 'sending', 'dont', 'involve', 'anything', 'shouldnt', 'imposed', 'anything', 'first', 'place', 'apologise']
['room']
['HEY', 'GIRL', 'R', 'U', 'HOPE', 'U', 'R', 'WELL', 'DEL', 'R', 'BAK', 'LONG', 'TIME', 'C', 'GIVE', 'CALL', 'SUM', 'TIME', 'LUCYxx']
['Kkhow', 'much', 'cost']
['Im', 'home']
['Dear', 'call', 'Tmorrowpls', 'accomodate']
['First', 'answer', 'question']
['Sunshine', 'Quiz', 'Wkly', 'Q', 'Win', 'top', 'Sony', 'DVD', 'player', 'u', 'know', 'country', 'Algarve', 'Txt', 'ansr', '82277', 'å£150', 'SPTyrone']
['Want', '2', 'get', 'laid', 'tonight', 'Want', 'real', 'Dogging', 'locations', 'sent', 'direct', '2', 'ur', 'mob', 'Join', 'UKs', 'largest', 'Dogging', 'Network', 'bt', 'Txting', 'GRAVEL', '69888', 'Nt', 'ec2a', '31pmsg150p']
['haf', 'msn', 'yijuehotmailcom']
['call', 'meet']
['check', 'rooms', 'befor', 'activities']
['Youll', 'rcv', 'msgs', 'chat', 'svc', 'FREE', 'Hardcore', 'services', 'text', 'GO', '69988', 'u', 'get', 'nothing', 'u', 'must', 'Age', 'Verify', 'yr', 'network', 'try']
['Got', 'c', 'lazy', 'type', 'forgot', 'Ì', 'lect', 'saw', 'pouch', 'like', 'v', 'nice']
['K', 'text', 'youre', 'way']
['Sir', 'Waiting', 'mail']
['swt', 'thought', 'Nver', 'get', 'tired', 'little', 'things', '4', 'lovable', 'persons', 'Cozsomtimes', 'little', 'things', 'occupy', 'biggest', 'part', 'Hearts', 'Gud', 'ni8']
['know', 'pls', 'open', 'back']
['Yes', 'see', 'ya', 'dot']
['Whats', 'staff', 'name', 'taking', 'class', 'us']
['FreeMsg', 'havent', 'replied', 'text', 'Im', 'Randy', 'sexy', 'female', 'live', 'local', 'Luv', 'hear', 'u', 'Netcollex', 'Ltd', '08700621170150p', 'per', 'msg', 'reply', 'Stop', 'end']
['Ummmawill', 'call', 'check', 'inour', 'life', 'begin', 'qatar', 'pls', 'pray', 'hard']
['Ki', 'deleted', 'contact']
['Sindu', 'got', 'job', 'birla', 'soft']
['wine', 'flowing', 'im', 'nevering']
['Yup', 'thk', 'cine', 'better', 'cos', 'need', '2', 'go', '2', 'plaza', 'mah']
['Ok', 'Ur', 'typical', 'reply']
['per', 'request', 'Melle', 'Melle', 'Oru', 'Minnaminunginte', 'Nurungu', 'Vettam', 'set', 'callertune', 'Callers', 'Press', '9', 'copy', 'friends', 'Callertune']
['everywhere', 'dirt', 'floor', 'windows', 'even', 'shirt', 'sometimes', 'open', 'mouth', 'comes', 'flowing', 'dream', 'world', 'without', 'half', 'chores', 'time', 'joy', 'lots', 'tv', 'shows', 'ill', 'see', 'guess', 'like', 'things', 'must', 'exist', 'like', 'rain', 'hail', 'mist', 'time', 'done', 'become', 'one']
['Aaooooright', 'work']
['Im', 'leaving', 'house']
['Hello', 'love', 'get', 'interview', 'today', 'happy', 'good', 'boy', 'think', 'meAre', 'missing']
['Customer', 'service', 'annoncement', 'New', 'Years', 'delivery', 'waiting', 'Please', 'call', '07046744435', 'arrange', 'delivery']
['winner', 'U', 'specially', 'selected', '2', 'receive', 'å£1000', 'cash', '4', 'holiday', 'flights', 'inc', 'speak', 'live', 'operator', '2', 'claim', '0871277810810']
['Keep', 'safe', 'need', 'miss', 'already', 'envy', 'everyone', 'sees', 'real', 'life']
['New', 'car', 'house', 'parentsi', 'new', 'job', 'hand']
['Im', 'love', 'Im', 'excited', 'day', 'spend', 'make', 'happy']
['PLS', 'STOP', 'bootydelious', '32F', 'inviting', 'friend', 'Reply', 'YES434', 'NO434', 'See', 'wwwSMSacubootydelious', 'STOP', 'Send', 'STOP', 'FRND', '62468']
['BangBabes', 'Ur', 'order', 'way', 'U', 'receive', 'Service', 'Msg', '2', 'download', 'UR', 'content', 'U', 'GoTo', 'wap', 'bangb', 'tv', 'UR', 'mobile', 'internetservice', 'menu']
['place', 'ur', 'points', 'e', 'cultures', 'module', 'already']
['URGENT', 'trying', 'contact', 'Last', 'weekends', 'draw', 'shows', 'å£900', 'prize', 'GUARANTEED', 'Call', '09061701939', 'Claim', 'code', 'S89', 'Valid', '12hrs']
['Hi', 'frnd', 'best', 'way', 'avoid', 'missunderstding', 'wit', 'beloved', 'ones']
['Great', 'escape', 'fancy', 'bridge', 'needs', 'lager', 'See', 'tomo']
['Yes', 'completely', 'formclark', 'also', 'utter', 'waste']
['Sir', 'need', 'AXIS', 'BANK', 'account', 'bank', 'address']
['Hmmm', 'Thk', 'sure', 'got', 'time', 'hop', 'ard', 'Ya', 'go', '4', 'free', 'abt', 'Muz', 'call', 'u', 'discuss', 'liao']
['time', 'coming', 'later']
['Bloody', 'hell', 'cant', 'believe', 'forgot', 'surname', 'Mr', 'Ill', 'give', 'u', 'clue', 'spanish', 'begins']
['Well', 'im', 'gonna', 'finish', 'bath', 'goodfine', 'night']
['Let', 'know', 'youve', 'got', 'money', 'carlos', 'make', 'call']
['U', 'still', 'going', 'mall']
['Turns', 'friends', 'staying', 'whole', 'show', 'wont', 'back', 'til', 'ltgt', 'feel', 'free', 'go', 'ahead', 'smoke', 'ltgt', 'worth']
['Text', 'doesnt', 'reply', 'let', 'know', 'log']
['Hi', 'spoke', 'MANEESHA', 'V', 'Wed', 'like', 'know', 'satisfied', 'experience', 'Reply', 'Toll', 'Free', 'Yes']
['lifted', 'hopes', 'offer', 'money', 'need', 'Especially', 'end', 'month', 'approaches', 'hurts', 'studying', 'Anyways', 'gr8', 'weekend']
['Lol', 'U', 'trust']
['ok', 'gentleman', 'treat', 'dignity', 'respect']
['guys', 'close']
['Going', 'nothing', 'greatbye']
['Hello', 'handsome', 'finding', 'job', 'lazy', 'Working', 'towards', 'getting', 'back', 'net', 'mummy', 'Wheres', 'boytoy', 'miss']
['Haha', 'awesome', 'minute']
['Please', 'call', 'customer', 'service', 'representative', 'FREEPHONE', '0808', '145', '4742', '9am11pm', 'guaranteed', 'å£1000', 'cash', 'å£5000', 'prize']
['got', 'Xmas', 'radio', 'times', 'get']
['jus', 'reached', 'home', 'go', 'bathe', 'first', 'sis', 'using', 'net', 'tell', 'u', 'finishes', 'k']
['unique', 'enough', 'Find', '30th', 'August', 'wwwareyouuniquecouk']
['Im', 'sorry', 'Ive', 'joined', 'league', 'people', 'dont', 'keep', 'touch', 'mean', 'great', 'deal', 'friend', 'times', 'even', 'great', 'personal', 'cost', 'great', 'week']
['Hi', 'finally', 'completed', 'course']
['stop', 'however', 'suggest', 'stays', 'someone', 'able', 'give', 'ors', 'every', 'stool']
['Hope', 'youve', 'settled', 'new', 'school', 'year', 'wishin', 'gr8', 'day']
['Gud', 'mrng', 'dear', 'hav', 'nice', 'day']
['u', 'got', 'persons', 'story']
['hamster', 'dead', 'Hey', 'tmr', 'meet', '1pm', 'orchard', 'mrt']
['Hi', 'Kate', 'evening', 'hope', 'see', 'tomorrow', 'bit', 'bloody', 'babyjontet', 'Txt', 'back', 'u', 'xxx']
['Found', 'ENC', 'ltgt']
['sent', 'ltgt', 'bucks']
['Hello', 'darlin', 'ive', 'finished', 'college', 'txt', 'u', 'finish', 'u', 'love', 'Kate', 'xxx']
['account', 'refilled', 'successfully', 'INR', 'ltDECIMALgt', 'KeralaCircle', 'prepaid', 'account', 'balance', 'Rs', 'ltDECIMALgt', 'Transaction', 'ID', 'KR', 'ltgt']
['Goodmorning', 'sleeping', 'ga']
['U', 'call', 'alter', '11', 'ok']
['ÌÏ', 'say', 'like', 'dat', 'dun', 'buy', 'ericsson', 'oso', 'cannot', 'oredi', 'lar']
['entered', 'cabin', 'PA', 'said', 'Happy', 'Bday', 'Boss', 'felt', 'special', 'askd', '4', 'lunch', 'lunch', 'invited', 'apartment', 'went']
['Aight', 'yo', 'dats', 'straight', 'dogg']
['please', 'give', 'us', 'connection', 'today', 'ltDECIMALgt', 'refund', 'bill']
['shoot', 'big', 'loads', 'get', 'ready']
['Whats', 'bruv', 'hope', 'great', 'break', 'rewarding', 'semester']
['Home', 'always', 'chat']
['Kkgoodstudy', 'well']
['Yup', 'Ì', 'noe', 'leh']
['Sounds', 'great', 'home']
['Finally', 'match', 'heading', 'towards', 'draw', 'prediction']
['Tired', 'havent', 'slept', 'well', 'past', 'nights']
['Easy', 'ahsen', 'got', 'selected', 'means', 'good']
['take', 'exam', 'march', '3']
['Yeah', 'think', 'use', 'gt', 'atm', 'register', 'sure', 'theres', 'anyway', 'help', 'let', 'know', 'sure', 'ready']
['Ok', 'prob', 'Take', 'ur', 'time']
['os', 'called', 'ubandu', 'run', 'without', 'installing', 'hard', 'diskyou', 'use', 'os', 'copy', 'important', 'files', 'system', 'give', 'repair', 'shop']
['Sorry', 'Ill', 'call', 'later']
['U', 'say', 'leh', 'course', 'nothing', 'happen', 'lar', 'say', 'v', 'romantic', 'jus', 'bit', 'lor', 'thk', 'e', 'nite', 'scenery', 'nice', 'leh']
['500', 'New', 'Mobiles', '2004', 'MUST', 'GO', 'Txt', 'NOKIA', '89545', 'collect', 'todayFrom', 'å£1', 'www4tcbiz', '2optout', '08718726270150gbpmtmsg18']
['Would', 'really', 'appreciate', 'call', 'need', 'someone', 'talk']
['u', 'meet', 'ur', 'dream', 'partner', 'soon', 'ur', 'career', '2', 'flyng', 'start', '2', 'find', 'free', 'txt', 'HORO', 'followed', 'ur', 'star', 'sign', 'e', 'g', 'HORO', 'ARIES']
['Hey', 'company', 'elama', 'po', 'mudyadhu']

In [14]:
# Vocabulary and  TF-IDF feature vector
vectorizer=TfidfVectorizer()
features=vectorizer.fit_transform(text_features)

In [15]:
print("first 10 Elements from the Dataset - spam.csv:")
print('-'*63)
text_features[:10]

first 10 Elements from the Dataset - spam.csv:
---------------------------------------------------------------

0    go jurong point crazi avail bugi n great world...
1                               ok lar joke wif u oni
2    free entri 2 wkli comp win fa cup final tkts 2...
3                 u dun say earli hor u c alreadi say
4           nah dont think goe usf live around though
5    freemsg hey darl 3 week word back id like fun ...
6       even brother like speak treat like aid patent
7    per request mell mell oru minnaminungint nurun...
8    winner valu network custom select receivea å£9...
9    mobil 11 month u r entitl updat latest colour ...
Name: Message, dtype: object

In [16]:
print("Last 10 Elements of the 'Dataset - spam.csv':")
print('-' * 63)
text_features[-10:]

Last 10 Elements of the 'Dataset - spam.csv':
---------------------------------------------------------------

5562    ok lor soni ericsson salesman ask shuhui say q...
5563                                  ard 6 like dat lor
5564               dont wait til least wednesday see get
5565                                             huh lei
5566    remind o2 get 250 pound free call credit detai...
5567    2nd time tri 2 contact u u å£750 pound prize 2...
5568                             ì b go esplanad fr home
5569                             piti mood soani suggest
5570    guy bitch act like id interest buy someth els ...
5571                                      rofl true name
Name: Message, dtype: object

In [17]:
print("Features from the 'Dataset - spam.csv':")
print('-' * 63)
print(features)

Features from the 'Dataset - spam.csv':
---------------------------------------------------------------
  (0, 3289)	0.14081218308843002
  (0, 4063)	0.3501112803835596
  (0, 5539)	0.23906338437276378
  (0, 2223)	0.2711370860940892
  (0, 1327)	0.2662313123328933
  (0, 1726)	0.29577542446330046
  (0, 3380)	0.19449555011263384
  (0, 7776)	0.2379272168522122
  (0, 4204)	0.29577542446330046
  (0, 1724)	0.33421906130459
  (0, 2006)	0.29577542446330046
  (0, 3342)	0.164475816719243
  (0, 1138)	0.3501112803835596
  (0, 7574)	0.19449555011263384
  (1, 5170)	0.2827396376113674
  (1, 4239)	0.42078899608869724
  (1, 4029)	0.47731294876998304
  (1, 7688)	0.44480400570972006
  (1, 5200)	0.5633086751818669
  (2, 3108)	0.1156013509460074
  (2, 2769)	0.35890157185696997
  (2, 7734)	0.1899683039634032
  (2, 2101)	0.19609614678919884
  (2, 7701)	0.145407091351942
  (2, 2886)	0.46833156720022556
  :	:
  (5568, 3289)	0.29668586321213597
  (5568, 3634)	0.3752780670596876
  (5568, 3097)	0.5769730291899227
  (5568, 2797)	0.6620015064495088
  (5569, 6756)	0.4714334480799934
  (5569, 4789)	0.4470332006149029
  (5569, 5475)	0.5375461940984255
  (5569, 6454)	0.5375461940984255
  (5570, 3108)	0.18670397745265893
  (5570, 7612)	0.20743149862457863
  (5570, 3764)	0.27184190203013203
  (5570, 4326)	0.18421270939092774
  (5570, 4969)	0.2445934820356672
  (5570, 7395)	0.24607202142912218
  (5570, 6476)	0.23912785879346776
  (5570, 1754)	0.23912785879346776
  (5570, 2728)	0.2841554454801746
  (5570, 3211)	0.32056763604388977
  (5570, 3431)	0.24387229420343928
  (5570, 3876)	0.30681162157411673
  (5570, 980)	0.3555373555878745
  (5570, 1542)	0.34061411390040397
  (5571, 4893)	0.48282258603770845
  (5571, 7230)	0.5375550566736839
  (5571, 6005)	0.6913153487782636

In [18]:
dataframe=pd.DataFrame(text_features)
dataframe.to_csv("Text Features.csv")

In [19]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
spam_dataset["Class"]=label_encoder.fit_transform(spam_dataset["Class"])
print("First 10 Elements of spam.csv,with the column-Class included:")
print('-'*73)
spam_dataset[:10]

First 10 Elements of spam.csv,with the column-Class included:
-------------------------------------------------------------------------

                                             Message  Class  Length
0  Go until jurong point, crazy.. Available only ...      0     111
1                      Ok lar... Joking wif u oni...      0      29
2  Free entry in 2 a wkly comp to win FA Cup fina...      1     155
3  U dun say so early hor... U c already then say...      0      49
4  Nah I don't think he goes to usf, he lives aro...      0      61
5  FreeMsg Hey there darling it's been 3 week's n...      1     148
6  Even my brother is not like to speak with me. ...      0      77
7  As per your request 'Melle Melle (Oru Minnamin...      0     160
8  WINNER!! As a valued network customer you have...      1     158
9  Had your mobile 11 months or more? U R entitle...      1     154

In [20]:
print("Last 10 Elements of 'spam.csv', with the 'Column - Class' included:")
print('-' * 73)
spam_dataset[-10:]

Last 10 Elements of 'spam.csv', with the 'Column - Class' included:
-------------------------------------------------------------------------

                                                Message  Class  Length
5562  Ok lor... Sony ericsson salesman... I ask shuh...      0      96
5563                                Ard 6 like dat lor.      0      19
5564  Why don't you wait 'til at least wednesday to ...      0      67
5565                                       Huh y lei...      0      12
5566  REMINDER FROM O2: To get 2.50 pounds free call...      1     147
5567  This is the 2nd time we have tried 2 contact u...      1     161
5568              Will Ì_ b going to esplanade fr home?      0      37
5569  Pity, * was in mood for that. So...any other s...      0      57
5570  The guy did some bitching but I acted like i'd...      0     125
5571                         Rofl. Its true to its name      0      26

In [21]:
print("Value counts for the Elements- ham and spam in the Dataset-spam.csv")
print('-'*80)
spam_dataset["Class"].value_counts()

Value counts for the Elements- ham and spam in the Dataset-spam.csv
--------------------------------------------------------------------------------

Class
0    4825
1     747
Name: count, dtype: int64

In [22]:
features_train,features_test,labels_train,labels_test=train_test_split(
    features,
    spam_dataset["Class"],
    test_size=0.3,
    random_state=111
)

# Implementing Regression Models

# Decision Tree Regressor

In [49]:
dtr=DecisionTreeRegressor()
dtr.fit(features_train,labels_train)

dtr_prediction=dtr.predict(features_test)
dtr_accuracy_score=accuracy_score(labels_test,dtr_prediction.round())*100
dtr_precision_score=precision_score(labels_test,dtr_prediction.round(),average="weighted")*100
dtr_recall_score=recall_score(labels_test,dtr_prediction.round(),average="weighted")*100
dtr_f1_score=f1_score(labels_test,dtr_prediction.round(),average="weighted")*100

print("Evaluation for Decision Tree Regressor".center(55,'_'))
print("Model Type:"+"\t",dtr)
print("Prediction:"+"\t",dtr_prediction.round())
print('_'*55)

print("Accuracy Score:"+"\t","{accuracy_score:.6f}%".format(accuracy_score=dtr_accuracy_score))
print("Precision Score:"+"\t","{precision_score:.6f}%".format(precision_score=dtr_precision_score))
print("Recall Score:"+"\t","{recall_score:.6f}%".format(recall_score=dtr_recall_score))
print("F1-Score:"+"\t","{f1_score:.6f}%".format(f1_score=dtr_f1_score))

print('-'*55)

_________Evaluation for Decision Tree Regressor________
Model Type:	 DecisionTreeRegressor()
Prediction:	 [0. 0. 0. ... 0. 0. 0.]
_______________________________________________________
Accuracy Score:	 96.351675%
Precision Score:	 96.311273%
Recall Score:	 96.351675%
F1-Score:	 96.328156%
-------------------------------------------------------

In [51]:
print("Confusion Matrix for Decision Tree Regressor -'Labels Test' & 'Prediction':")
print('_'*79)
print(confusion_matrix(labels_test,dtr_prediction.round()))

Confusion Matrix for Decision Tree Regressor -'Labels Test' & 'Prediction':
_______________________________________________________________________________
[[1413   27]
 [  34  198]]

In [55]:
print("Classification Report for Decision Tree Regressor - 'Labels Test' & 'Prediction':")
print('_' * 83)
print(classification_report(labels_test, dtr_prediction.round()))

Classification Report for Decision Tree Regressor - 'Labels Test' & 'Prediction':
___________________________________________________________________________________
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      1440
           1       0.88      0.85      0.87       232

    accuracy                           0.96      1672
   macro avg       0.93      0.92      0.92      1672
weighted avg       0.96      0.96      0.96      1672

# Random Forest Regressor

In [58]:
rfr=RandomForestRegressor()
rfr.fit(features_train,labels_train)

rfr_prediction = rfr.predict(features_test)
rfr_accuracy_score = accuracy_score(labels_test, rfr_prediction.round()) * 100
rfr_precision_score = precision_score(labels_test, rfr_prediction.round(), average="weighted") * 100
rfr_recall_score = recall_score(labels_test, rfr_prediction.round(), average="weighted") * 100
rfr_f1_score = f1_score(labels_test, rfr_prediction.round(), average="weighted") * 100

print("Evaluation for Random Forest Regressor".center(60, '_'))
print("Model Type:" + "\t", rfr)
print("Prediction:" + "\t", rfr_prediction)
print('-' * 60)

print("Accuracy Score:" + "\t", "{accuracy_score:.6f}%".format(accuracy_score=rfr_accuracy_score))
print("Precision Score:", "{precision_score:.6f}%".format(precision_score=rfr_precision_score))
print("Recall Score:" + "\t", "{recall_score:.6f}%".format(recall_score=rfr_recall_score))
print("F1-Score:" + "\t", "{f1_score:.6f}%".format(f1_score=rfr_f1_score))
print('-' * 60)

___________Evaluation for Random Forest Regressor___________
Model Type:	 RandomForestRegressor()
Prediction:	 [0.   0.   0.   ... 0.   0.03 0.  ]
------------------------------------------------------------
Accuracy Score:	 96.590909%
Precision Score: 96.517291%
Recall Score:	 96.590909%
F1-Score:	 96.522446%
------------------------------------------------------------

In [60]:
print("Confusion Matrix for Random Forest Regressor - 'Labels Test' & 'Prediction':")
print('_' * 83)
print(confusion_matrix(labels_test, rfr_prediction.round()))

Confusion Matrix for Random Forest Regressor - 'Labels Test' & 'Prediction':
___________________________________________________________________________________
[[1422   18]
 [  39  193]]

In [62]:
print("Classification Report for Random Forest Regressor - 'Labels Test' & 'Prediction':")
print('_' * 85)
print(classification_report(labels_test, rfr_prediction.round()))

Classification Report for Random Forest Regressor - 'Labels Test' & 'Prediction':
_____________________________________________________________________________________
              precision    recall  f1-score   support

           0       0.97      0.99      0.98      1440
           1       0.91      0.83      0.87       232

    accuracy                           0.97      1672
   macro avg       0.94      0.91      0.93      1672
weighted avg       0.97      0.97      0.97      1672